from . import campaign
from . import campaign_element
from . import campaign_tag
from . import models
from . import res_country
from . import res_partner
from . import template
from . import template_group
from . import url
